"""
plot_cot_completeness.py — Visualize chain-of-thought truncation rates.

Reads the CSV generated by parse_thoughts.py and creates a chart showing
how often the model's reasoning was incomplete (truncated before outputting
STRATEGY/ACTION) across runs, grouped by tax rate and pressure condition.

Usage:
    python plot_cot_completeness.py                              # defaults
    python plot_cot_completeness.py --csv incomplete_cot.csv     # custom CSV
    python plot_cot_completeness.py --out cot_chart.png          # custom output
"""

import os
import argparse
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ── Theme (matches blog plots) ───────────────────────────────────────────────
BG       = "#FAF8F5"
TEXT     = "#2D2A26"
GRID     = (0.78, 0.76, 0.72, 0.4)
OLIVE    = "#6B7F3B"
PLUM     = "#8B3A6B"
AMBER    = "#C4893B"
SPINE    = "#D1CEC8"
DPI      = 150


def style_ax(ax, title=""):
    ax.set_facecolor(BG)
    ax.set_title(title, color=TEXT, fontsize=13, fontweight="bold", pad=12)
    ax.tick_params(colors=TEXT, labelsize=9)
    ax.xaxis.label.set_color(TEXT)
    ax.yaxis.label.set_color(TEXT)
    for spine in ax.spines.values():
        spine.set_edgecolor(SPINE)
    ax.grid(axis="y", color=GRID, linewidth=0.5)


def plot_per_run(df, out_path):
    """Bar chart: incomplete turns per run, colored by pressure."""
    fig, ax = plt.subplots(figsize=(14, 6), facecolor=BG)
    style_ax(ax, "Chain-of-thought truncation — incomplete turns per run")

    x = np.arange(len(df))
    colors = [PLUM if p == "Yes" else OLIVE for p in df["Pressure"]]

    # Bar = incomplete %, with total turns as reference
    incomplete_pct = (df["Incomplete Turns"] / df["Total Turns"] * 100).values

    bars = ax.bar(x, incomplete_pct, color=colors, width=0.7, zorder=3)

    # Value labels
    for bar, val, inc, total in zip(bars, incomplete_pct,
                                     df["Incomplete Turns"], df["Total Turns"]):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                f"{val:.0f}%\n({inc}/{total})",
                ha="center", va="bottom", color=TEXT, fontsize=7)

    # Labels
    labels = [f"{row['Run Name']}\n{int(row['Tax %'])}% {'P' if row['Pressure']=='Yes' else 'NP'}"
              for _, row in df.iterrows()]
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=7.5)
    ax.set_ylabel("Incomplete turns (%)")
    ax.set_ylim(0, max(incomplete_pct.max() * 1.3, 10))

    # Legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=OLIVE, label="No pressure"),
        Patch(facecolor=PLUM, label="With pressure"),
    ]
    ax.legend(handles=legend_elements, facecolor="#EDEAE4", labelcolor=TEXT,
              fontsize=9, loc="upper right")

    path = out_path.replace(".png", "_per_run.png")
    plt.savefig(path, dpi=DPI, bbox_inches="tight", facecolor=BG)
    plt.close(fig)
    print(f"  Saved → {path}")


def plot_by_tax_and_pressure(df, out_path):
    """Grouped bar chart: avg truncation rate by tax % and pressure."""
    fig, ax = plt.subplots(figsize=(10, 6), facecolor=BG)
    style_ax(ax, "Average CoT truncation rate — by tax rate and pressure")

    df["incomplete_pct"] = df["Incomplete Turns"] / df["Total Turns"] * 100

    # Group by tax and pressure
    tax_rates = sorted(df["Tax %"].unique())
    groups = []
    for tax in tax_rates:
        np_val = df[(df["Tax %"] == tax) & (df["Pressure"] == "No")]["incomplete_pct"].mean()
        p_val = df[(df["Tax %"] == tax) & (df["Pressure"] == "Yes")]["incomplete_pct"].mean()
        # Only include if at least one condition has data
        if not (np.isnan(np_val) and np.isnan(p_val)):
            groups.append({
                "tax": f"{int(tax)}% tax",
                "no_pressure": np_val if not np.isnan(np_val) else 0,
                "pressure": p_val if not np.isnan(p_val) else 0,
                "has_np": not np.isnan(np_val),
                "has_p": not np.isnan(p_val),
            })

    if not groups:
        print("  Skipping grouped chart — no data")
        return

    labels = [g["tax"] for g in groups]
    np_vals = [g["no_pressure"] for g in groups]
    p_vals = [g["pressure"] for g in groups]

    x = np.arange(len(labels))
    w = 0.32

    bars1 = ax.bar(x - w/2, np_vals, w, color=OLIVE, label="No pressure", zorder=3)
    bars2 = ax.bar(x + w/2, p_vals, w, color=PLUM, label="With pressure", zorder=3)

    # Value labels
    for bar, val in zip(bars1, np_vals):
        if val > 0:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                    f"{val:.0f}%", ha="center", va="bottom", color=TEXT, fontsize=10)
    for bar, val in zip(bars2, p_vals):
        if val > 0:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                    f"{val:.0f}%", ha="center", va="bottom", color=TEXT, fontsize=10)

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=11)
    ax.set_ylabel("Avg incomplete turns (%)")
    ax.set_ylim(0, max(max(np_vals + p_vals) * 1.3, 10))
    ax.legend(facecolor="#EDEAE4", labelcolor=TEXT, fontsize=9)

    path = out_path.replace(".png", "_by_tax.png")
    plt.savefig(path, dpi=DPI, bbox_inches="tight", facecolor=BG)
    plt.close(fig)
    print(f"  Saved → {path}")


def plot_completion_summary(df, out_path):
    """Horizontal bar: completion rate per run, sorted."""
    fig, ax = plt.subplots(figsize=(10, 8), facecolor=BG)
    style_ax(ax, "Chain-of-thought completion rate per run")

    sorted_df = df.sort_values("Completion Rate %", ascending=True).reset_index(drop=True)
    sorted_df["Completion Rate %"] = sorted_df["Completion Rate %"].astype(float)

    y = np.arange(len(sorted_df))
    colors = [PLUM if p == "Yes" else OLIVE for p in sorted_df["Pressure"]]

    bars = ax.barh(y, sorted_df["Completion Rate %"], color=colors,
                   height=0.65, zorder=3)

    for bar, val in zip(bars, sorted_df["Completion Rate %"]):
        ax.text(bar.get_width() + 0.8, bar.get_y() + bar.get_height()/2,
                f"{val:.0f}%", ha="left", va="center", color=TEXT, fontsize=8)

    labels = [f"{row['Run Name']} ({int(row['Tax %'])}%)"
              for _, row in sorted_df.iterrows()]
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel("Completion rate (%)")
    ax.set_xlim(0, 110)

    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=OLIVE, label="No pressure"),
        Patch(facecolor=PLUM, label="With pressure"),
    ]
    ax.legend(handles=legend_elements, facecolor="#EDEAE4", labelcolor=TEXT,
              fontsize=9, loc="lower right")

    path = out_path.replace(".png", "_completion.png")
    plt.savefig(path, dpi=DPI, bbox_inches="tight", facecolor=BG)
    plt.close(fig)
    print(f"  Saved → {path}")


def main():
    parser = argparse.ArgumentParser(
        description="Plot chain-of-thought truncation rates"
    )
    parser.add_argument("--csv", type=str, default="incomplete_cot.csv",
                        help="CSV from parse_thoughts.py")
    parser.add_argument("--out", type=str, default="cot_truncation.png",
                        help="Output PNG base name")
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f"  ERROR: CSV not found: {args.csv}")
        print(f"  Run parse_thoughts.py first to generate it.")
        return

    df = pd.read_csv(args.csv)
    print(f"  Loaded {len(df)} runs from {args.csv}")
    print()

    plot_per_run(df, args.out)
    plot_by_tax_and_pressure(df, args.out)
    plot_completion_summary(df, args.out)

    print()
    print("  Done.")


if __name__ == "__main__":
    main()
